#!/usr/bin/bash

DEFAULT_MQTT_HOST=localhost
DEFAULT_TALK_TOPIC=talk

MQTT_HOST=${MQTT_HOST:-$DEFAULT_MQTT_HOST}
TALK_TOPIC=${TALK_TOPIC:-$DEFAULT_TALK_TOPIC}

if ! command -v mosquitto_sub >/dev/null; then
  echo "missing: mosquitto_sub # fix: sudo apt install mosquitto_clients"
  return 1
fi

if ! command -v say >/dev/null; then
  echo "missing: say # fix ... t3x or solid-octo-goggles or dectalk"
  return 1
fi

# TODO add either a PID based lockfile or 
# single tmux named session logic to
# prevent multiple talk clients at once ...
# we only have one speaker!

echo "starting talk client pipe to say"
echo "mosquitto_sub -h \"$MQTT_HOST\" -t \"$TALK_TOPIC\""
mosquitto_sub -h "$MQTT_HOST" -t "$TALK_TOPIC" | tee /dev/tty | say
